### PR TITLE
Add Git SHA api endpoint.

### PR DESCRIPTION
**Pull request by trilleplay**

### CODE REVIEW

**Review by oliverlevay — APPROVED** [review]
should work! unclear if this will work when deployed, but we will find out

**Comment by danieladugyan** [comment]
> should work! unclear if this will work when deployed, but we will find out

I'm pretty sure it won't unfortunately. Maybe something along these lines? https://stackoverflow.com/questions/70436753/how-to-add-commit-hash-into-reactjs-vite-config-js

**Review by oliverlevay — CHANGES_REQUESTED** [review]
I agree with Daniel

**Comment by danieladugyan** [comment]
This PR has been stale for a while, so I'm closing it for now. Anyone can feel free to reopen this if they want to resume work on this feature.

**Pull request closed without merging**
