### PR TITLE
Add verbose door names

### PR DESCRIPTION
**Pull request by fnurkla**
This PR adds a verbose name field to doors to make it easier for people to understand which door access policies and the like refer to.

### CODE REVIEW

**Comment by alfredgrip** [comment]
Do we have to allow null values for `verbose_name`? It's not like we insert a new door into our database without having a name for it 🤔

**Comment by fnurkla** [comment]
No, I guess not. I cam change that.

**Comment by fnurkla** [comment]
I realized that I forgot to fix the database migration. Can I just edit it and add in the `NOT NULL` at the end or is that blasphemous?

**Comment by fnurkla** [comment]
Should be good to go now.

**Review by Isak-Kallini — CHANGES_REQUESTED** [review]
I get an error when running `sh dev/setup_db.sh`:
`ERROR: column "verbose_name" of relation "doors" contains null values` from the migration and `The column 'verbose_name' does not exist in the current database.` from doors.ts.
It looks like it tries to add the column but there's already rows in the table and it gives an error because there are null values in the new column. Then it fails in seeding as well since the column wasn't created. 
After a quick google the easiest way to fix this seems like adding a default value to the column. Another option is to initially allow null values, seed it and then alter it to not allow null values, but I'm not sure how to do this with Prisma.

**Comment by fnurkla** [comment]
Alright, I'll check on this tonight!

**Comment by fnurkla** [comment]
Alright, so this should fix that problem. This time I actually checked 😅

**Review by Isak-Kallini — APPROVED** [review]
Looks good, nice work!

**Pull request merged**
