### PR TITLE
23 bookings page

### PR DESCRIPTION
**Pull request by BlixtSamme**
Bookings are finally here. This version should be sufficient for release but the goal is however to optimize it later

### CODE REVIEW

**Comment by danieladugyan** [comment]
Welp, I seem to have messed up merging with main 😅 I'll try and fix it.

**Comment by danieladugyan** [comment]
Alright, so I got a bit carried away and continued building on your work. I should really have done that in another PR. Anyways, check it out and make sure I didn't do anything stupid. After that I'd say we can merge this. Good job! 👍

**Review by danieladugyan — APPROVED** [review]
Alright, so I got a bit carried away and continued building on your work. I should really have done that in another PR. Anyways, check it out and make sure I didn't do anything stupid. After that I'd say we can merge this. Great job! 👍

**Comment by BlixtSamme** [comment]
LGTM

**Pull request merged**
